cpi_config:
  start_date: "2019-01-01"
  # area_code: S35A
  area_code: "0000"
  item_codes:
    - SA0
    # - SA0E
    # - SA0L1
    # - SA0L1E
    # - SA0L2
    # - SA0L5
    # - SA0LE
    # - SA0R
    # - SA311
    # - SAA
    # - SAA1
    # - SAA2
    # - SAC
    # - SACE
    # - SACL1
    # - SACL11
    # - SACL1E
    # - SAD
    # - SAE
    # - SAE1
    # - SAE2
    # - SAE21
    # - SAEC
    # - SAES
    # - SAF
    # - SAF1
    # - SAF11
    # - SAF111
    # - SAF112
    # - SAF1121
    # - SAF11211
    # - SAF113
    # - SAF1131
    # - SAF114
    # - SAF115
    # - SAF116
    # - SAG
    # - SAG1
    # - SAGC
    # - SAGS
    # - SAH
    # - SAH1
    # - SAH2
    # - SAH21
    # - SAH3
    # - SAH31
    # - SAM
    # - SAM1
    # - SAM2
    # - SAN
    # - SAN1D
    # - SANL1
    # - SANL11
    # - SANL113
    # - SANL13
    # - SAR
    # - SARC
    # - SARS
    # - SAS
    # - SAS24
    # - SAS2RS
    # - SAS367
    # - SAS4
    # - SASL2RS
    # - SASL5
    # - SASLE
    # - SAT
    # - SAT1
    # - SATCLTB
    # - SEAA
    # - SEAA01
    # - SEAA02
    # - SEAA03
    # - SEAA04
    # - SEAB
    # - SEAC
    # - SEAC01
    # - SEAC02
    # - SEAC03
    # - SEAC04
    # - SEAD
    # - SEAE
    # - SEAE01
    # - SEAE02
    # - SEAE03
    # - SEAF
    # - SEAG
    # - SEAG01
    # - SEAG02
    # - SEEA
    # - SEEB
    # - SEEB01
    # - SEEB02
    # - SEEB03
    # - SEEB04
    # - SEEC
    # - SEEC01
    # - SEEC02
    # - SEED
    # - SEED03
    # - SEED04
    # - SEEE
    # - SEEE01
    # - SEEE02
    # - SEEE03
    # - SEEE04
    # - SEEEC
    # - SEFA
    # - SEFA01
    # - SEFA02
    # - SEFA03
    # - SEFB
    # - SEFB01
    # - SEFB02
    # - SEFB03
    # - SEFB04
    # - SEFC
    # - SEFC01
    # - SEFC02
    # - SEFC03
    # - SEFC04
    # - SEFD
    # - SEFD01
    # - SEFD02
    # - SEFD03
    # - SEFD04
    # - SEFE
    # - SEFF
    # - SEFF01
    # - SEFF02
    # - SEFG
    # - SEFG01
    # - SEFG02
    # - SEFH
    # - SEFJ
    # - SEFJ01
    # - SEFJ02
    # - SEFJ03
    # - SEFJ04
    # - SEFK
    # - SEFK01
    # - SEFK02
    # - SEFK03
    # - SEFK04
    # - SEFL
    # - SEFL01
    # - SEFL02
    # - SEFL03
    # - SEFL04
    # - SEFM
    # - SEFM01
    # - SEFM02
    # - SEFM03
    # - SEFN
    # - SEFN01
    # - SEFN02
    # - SEFN03
    # - SEFP
    # - SEFP01
    # - SEFP02
    # - SEFR
    # - SEFR01
    # - SEFR02
    # - SEFR03
    # - SEFS
    # - SEFS01
    # - SEFS02
    # - SEFS03
    # - SEFT
    # - SEFT01
    # - SEFT02
    # - SEFT03
    # - SEFT04
    # - SEFT05
    # - SEFT06
    # - SEFV
    # - SEFV01
    # - SEFV02
    # - SEFV03
    # - SEFV04
    # - SEFV05
    # - SEFW
    # - SEFW01
    # - SEFW02
    # - SEFW03
    # - SEFX
    # - SEGA
    # - SEGA01
    # - SEGA02
    # - SEGB
    # - SEGB01
    # - SEGB02
    # - SEGC
    # - SEGC01
    # - SEGD
    # - SEGD01
    # - SEGD02
    # - SEGD03
    # - SEGD04
    # - SEGD05
    # - SEGE
    # - SEHA
    # - SEHB
    # - SEHB01
    # - SEHB02
    # - SEHC
    # - SEHC01
    # - SEHD
    # - SEHE
    # - SEHE01
    # - SEHE02
    # - SEHF
    # - SEHF01
    # - SEHF02
    # - SEHG
    # - SEHG01
    # - SEHG02
    # - SEHH
    # - SEHH01
    # - SEHH02
    # - SEHH03
    # - SEHJ
    # - SEHJ01
    # - SEHJ02
    # - SEHJ03
    # - SEHK
    # - SEHK01
    # - SEHK02
    # - SEHL
    # - SEHL01
    # - SEHL02
    # - SEHL03
    # - SEHL04
    # - SEHM
    # - SEHM01
    # - SEHM02
    # - SEHN
    # - SEHN01
    # - SEHN02
    # - SEHN03
    # - SEHP
    # - SEHP01
    # - SEHP02
    # - SEHP03
    # - SEHP04
    # - SEMC
    # - SEMC01
    # - SEMC02
    # - SEMC03
    # - SEMC04
    # - SEMD
    # - SEMD01
    # - SEMD02
    # - SEMD03
    # - SEME
    # - SEMF
    # - SEMF01
    # - SEMF02
    # - SEMG
    # - SERA
    # - SERA01
    # - SERA02
    # - SERA03
    # - SERA04
    # - SERA05
    # - SERA06
    # - SERAC
    # - SERAS
    # - SERB
    # - SERB01
    # - SERB02
    # - SERC
    # - SERC01
    # - SERC02
    # - SERD
    # - SERD01
    # - SERD02
    # - SERE
    # - SERE01
    # - SERE02
    # - SERE03
    # - SERF
    # - SERF01
    # - SERF02
    # - SERF03
    # - SERG
    # - SERG01
    # - SERG02
    # - SETA
    # - SETA01
    # - SETA02
    # - SETA03
    # - SETA04
    # - SETB
    # - SETB01
    # - SETB02
    # - SETC
    # - SETC01
    # - SETC02
    # - SETD
    # - SETD01
    # - SETD02
    # - SETD03
    # - SETE
    # - SETF
    # - SETF01
    # - SETF03
    # - SETG
    # - SETG01
    # - SETG02
    # - SETG03
    # - SS47014
    # - SS47015
    # - SS47016
    # - SS5702
    # - SS5703
